
services:
  fe:
    build:
      context: frontend/.
      labels:
        - com.ibm.mq.app=mqapp
    image: frontend:0.1
    ports:
      - 3000:3000    
    networks:
      - app-pubic-network
      - qm1network
    depends_on:
      - be
    labels:
      - com.ibm.mq.app=mqapp 
  be:
    build:
      context: backend/.
      labels:
        - com.ibm.mq.app=mqapp
    image: backend:0.1
    ports:
      - 8080:8080    
    networks:
      - app-pubic-network
      - qm1network    
    labels:
      - com.ibm.mq.app=mqapp
volumes:
  qm1data:
    driver_opts:
      gid: 0
    labels:
      - com.ibm.mq=qm1
networks:
  qm1network:
    labels:
      - com.ibm.mq=qm1
  app-pubic-network:
    labels:
      - com.ibm.mq.app=mqapp
